apiVersion: v1
kind: Service
metadata:
  name: gpsd-map-mgmt
  namespace: gpsd
spec:
  selector:
    app: gpsd-map-mgmt
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
      nodePort: 30070
  type: NodePort

