name: Deploy Helm Chart on Remote Server

on:
    workflow_run:
      workflows: ["Docker Build, Push, Run using Makefile"]
      types:
          - completed

jobs:
  deploy_helm:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} 
    steps:

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_SERVER }} >> ~/.ssh/known_hosts

      - name: Connect to Remote Server & Update Helm Repo
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_SERVER }} << 'EOF'
            cd /srv/shared
            helm repo add ${{ secrets.SERVICE_NAME }} https://${{ secrets.REMOTE_CHART_REPOSITORY }}/${{ secrets.SERVICE_NAME }}/            
            helm repo update
            helm repo list
          EOF
