name: Update Helm Chart and Execute Makefile

on:
  workflow_run:
    workflows: ["Docker Build, Push, Run using Makefile"]
    types:
        - completed

permissions:
  contents: write 

jobs:
  update_chart:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Extract Git Tag for Versioning
      - name: Extract Git Tag
        id: tag
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Update values.yaml
        run: |
          sed -i 's|tag: ".*"|tag: "${{ env.TAG_VERSION }}"|' helm/values.yaml

      - name: Update Chart.yaml
        run: |
            NEW_VERSION=$(echo "${{ env.TAG_VERSION }}" | sed 's/^v//')
            sed -i "s/^version:.*/version: $NEW_VERSION/" helm/Chart.yaml

      - name: Commit Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add helm/values.yaml helm/Chart.yaml
          git commit -m "Update Helm chart to tag ${{ env.TAG_VERSION }}"
          git push origin main

      - name: Execute Makefile Command
        run: make gh-pages-publish
